# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ba580LBveJwKIODNNG2bGEnZXUgNuHOa
"""

print ("halo dunia!")
print ("belajar AI!")
print ("Yes!")